---
# install nginx
- name: Install nginx (ubuntu)
  apt:
    name: nginx
    state: present

# setup Nginx config files
- name: Create nginx config
  template: src=default.ubuntu dest=/etc/nginx/sites-available/default
  # trigger handler whenever config file changes
  notify: restart nginx

# set the home page
- name: Set nginx home page
  copy: src=index.html dest=/var/www/html/index.html

# start nginx
- name: Start nginx
  service: name=nginx state=started enabled=yes

# verify web site
- name: Verify web site
  action: uri url=http://{{ item }} return_content=yes
  loop: "{{ groups['ec2hosts'] }}"
  register: webpage

- name: fail with message
  fail:
    msg: 'service is not up'
  when: "'New web site run by Nginx' not in item.content"
  loop: "{{ webpage.results }}"
