ec2_access_key: "{{ vault_ec2_access_key }}"
ec2_secret_key: "{{ vault_ec2_secret_key }}"
ec2_region: <AWS Region, e.g. ap-southeast-1>

# ami_id:
# ami-0992fc94ca0f1415a (amazon)
# ami-059b6d3840b03d6dd (ubuntu)
ami_id: ami-059b6d3840b03d6dd

# remote_user:
# ec2-user (amazon)
# ubuntu (ubuntu)
remote_user: ubuntu

key_name: <AWS key pair name>
ec2_security_group: <AWS security group name, e.g. default>
